/*
This file is part of the KubeVirt project

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Copyright The KubeVirt Authors.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	corev1alpha1 "kubevirt.io/api/core/v1alpha1"
	scheme "kubevirt.io/client-go/kubevirt/scheme"
)

// ManagedClaimProvisionersGetter has a method to return a ManagedClaimProvisionerInterface.
// A group's client should implement this interface.
type ManagedClaimProvisionersGetter interface {
	ManagedClaimProvisioners() ManagedClaimProvisionerInterface
}

// ManagedClaimProvisionerInterface has methods to work with ManagedClaimProvisioner resources.
type ManagedClaimProvisionerInterface interface {
	Create(ctx context.Context, managedClaimProvisioner *corev1alpha1.ManagedClaimProvisioner, opts v1.CreateOptions) (*corev1alpha1.ManagedClaimProvisioner, error)
	Update(ctx context.Context, managedClaimProvisioner *corev1alpha1.ManagedClaimProvisioner, opts v1.UpdateOptions) (*corev1alpha1.ManagedClaimProvisioner, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*corev1alpha1.ManagedClaimProvisioner, error)
	List(ctx context.Context, opts v1.ListOptions) (*corev1alpha1.ManagedClaimProvisionerList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *corev1alpha1.ManagedClaimProvisioner, err error)
	ManagedClaimProvisionerExpansion
}

// managedClaimProvisioners implements ManagedClaimProvisionerInterface
type managedClaimProvisioners struct {
	*gentype.ClientWithList[*corev1alpha1.ManagedClaimProvisioner, *corev1alpha1.ManagedClaimProvisionerList]
}

// newManagedClaimProvisioners returns a ManagedClaimProvisioners
func newManagedClaimProvisioners(c *KubevirtV1alpha1Client) *managedClaimProvisioners {
	return &managedClaimProvisioners{
		gentype.NewClientWithList[*corev1alpha1.ManagedClaimProvisioner, *corev1alpha1.ManagedClaimProvisionerList](
			"managedclaimprovisioners",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *corev1alpha1.ManagedClaimProvisioner { return &corev1alpha1.ManagedClaimProvisioner{} },
			func() *corev1alpha1.ManagedClaimProvisionerList { return &corev1alpha1.ManagedClaimProvisionerList{} },
		),
	}
}
