// Code generated by swagger-doc. DO NOT EDIT.

package v1alpha1

func (ManagedClaimProvisioner) SwaggerDoc() map[string]string {
	return map[string]string{
		"":     "ManagedClaimProvisioner encodes the DeviceClass mappings and the name of the\nprovisioner controller used to generate a ResourceClaim for a VMI.\n\nAdmins create ManagedClaimProvisioner objects; users reference one by name\nfrom vmi.spec.resourceClaims[].managedClaimProvisionerName and declare their\ndevices as usual. The referenced provisioner controller receives every device\ndeclaration for the managed claim and assembles the ResourceClaim.\n\nThis resource is in alpha and requires the ManagedDRAClaims feature gate.",
		"spec": "Spec defines the provisioner controller and its DeviceClass mappings.",
	}
}

func (ManagedClaimProvisionerList) SwaggerDoc() map[string]string {
	return map[string]string{
		"":      "+k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object",
		"items": "+listType=atomic",
	}
}

func (ManagedClaimProvisionerSpec) SwaggerDoc() map[string]string {
	return map[string]string{
		"provisioner": "Provisioner identifies the controller responsible for claim generation.\nKubeVirt ships policy.kubevirt.io/aligner, which applies PCIe-root and\nNUMA topology alignment. Third-party controllers use their own name.\n\nA managed claim is only reconciled once a controller serving this\nprovisioner name is running; until then the launcher pod stays pending.",
		"deviceTypes": "DeviceTypes maps VMI device declarations to DeviceClass names and\noptional driver-specific configuration.\n\nEach entry's name must be unique and one of cpu, gpu, hostDevice, or\nnetwork. Every device type referenced by a device in the managed claim\nmust have an entry here.\n+listType=map\n+listMapKey=name",
	}
}

func (ManagedClaimDeviceType) SwaggerDoc() map[string]string {
	return map[string]string{
		"name":            "Name is the VMI device declaration this entry configures: one of\ncpu, gpu, hostDevice, or network.",
		"deviceClassName": "DeviceClassName is the DeviceClass used for every request generated for\nthis device type.",
		"opaque":          "Opaque is driver-specific configuration. When set, the provisioner\nrenders a DeviceClaimConfiguration into the generated\nResourceClaim.spec.devices.config, with requests set to every generated\nrequest for this device type.\n+optional",
	}
}
